# Generated by Django 2.1.5 on 2019-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='recommend_user_list',
        ),
    ]
