# Generated by Django 2.2.1 on 2019-05-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('cover_url', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
